import { detectEntryPoints } from "./detectors/entry-points.js";
import { buildOverview } from "./detectors/overview.js";
import { detectProjectType } from "./detectors/project-type.js";
import {
    detectReusableSystem,
    detectSharedUi,
    detectUtilityDirs,
} from "./detectors/reusable-system.js";
import { detectRiskAreas } from "./detectors/risk-areas.js";
import {
    getClosestStructurePath,
    detectStructure,
    getStructureDescription,
} from "./detectors/structure.js";
import { exists, isDirectory } from "./fs-utils.js";
import { detectPackageMetadata, detectTechStack } from "./package-utils.js";
import { getProjectMdUpdate, updateProjectMd } from "./writers/project-md.js";

function formatDescriptiveList(items) {
    return items.map((item) =>
        item.description ? `- ${item.label} -> ${item.description}` : `- ${item.label}`,
    );
}

function extractReferencedDirectories(lines) {
    const referencedDirs = new Set();
    const pathMatches = lines.flatMap(
        (line) => line.match(/(?:\.[A-Za-z0-9_-]+|[A-Za-z0-9_-]+)(?:\/[A-Za-z0-9_.-]+)+\/?/g) || [],
    );

    for (const match of pathMatches) {
        const normalized = match.replace(/`/g, "").replace(/\/+$/, "");
        const mappedStructurePath = getClosestStructurePath(normalized);

        if (mappedStructurePath && exists(mappedStructurePath)) {
            referencedDirs.add(mappedStructurePath);
            continue;
        }

        if (isDirectory(normalized)) {
            referencedDirs.add(normalized);
            continue;
        }

        const lastSlashIndex = normalized.lastIndexOf("/");
        if (lastSlashIndex === -1) {
            continue;
        }

        const parentDir = normalized.slice(0, lastSlashIndex);
        const mappedParentPath = getClosestStructurePath(parentDir);

        if (mappedParentPath && exists(mappedParentPath)) {
            referencedDirs.add(mappedParentPath);
            continue;
        }

        if (parentDir && isDirectory(parentDir)) {
            referencedDirs.add(parentDir);
        }
    }

    return [...referencedDirs];
}

function mergeStructureWithReferences(structure, reusableSystem, risks) {
    const structureByLabel = new Map(structure.map((item) => [item.label, item]));
    const referencedDirs = extractReferencedDirectories([
        ...reusableSystem.sections.flatMap((section) => section.items),
        ...risks,
    ]);

    for (const dir of referencedDirs) {
        const label = `${dir}/`;

        if (structureByLabel.has(label)) {
            continue;
        }

        structureByLabel.set(label, {
            label,
            description:
                getStructureDescription(dir) ||
                "referenced project directory with shared implementation significance",
        });
    }

    return [...structureByLabel.values()];
}

export function generateProjectMdContent() {
    const projectType = detectProjectType();
    const techStack = detectTechStack(projectType);
    const packageMetadata = detectPackageMetadata();
    const sharedUi = detectSharedUi();
    const utilityDirs = detectUtilityDirs();
    const reusableSystem = detectReusableSystem(
        projectType,
        sharedUi,
        utilityDirs,
    );
    const structure = detectStructure(projectType);
    const risks = detectRiskAreas(projectType, structure, sharedUi);
    const mergedStructure = mergeStructureWithReferences(
        structure,
        reusableSystem,
        risks,
    );
    const entryPoints = detectEntryPoints(projectType);
    const overview = buildOverview(projectType, techStack);

    const lines = [
        "This section is automatically generated by `ai-dev-workflow scan`.",
        "Do not edit manually.",
        "",
        "## Project Type",
        `- ${projectType}`,
        "",
        "## Overview",
        ...overview,
        "",
        "## Tech Stack",
    ];

    if (techStack.length === 0) {
        lines.push("- Not clearly detected");
    } else {
        lines.push(...techStack.map((item) => `- ${item}`));
    }

    lines.push("", "## Package Metadata");
    if (!packageMetadata) {
        lines.push("- package.json not found");
    } else {
        if (packageMetadata.name) {
            lines.push(`- name: ${packageMetadata.name}`);
        }
        if (packageMetadata.version) {
            lines.push(`- version: ${packageMetadata.version}`);
        }
        if (packageMetadata.type) {
            lines.push(`- module type: ${packageMetadata.type}`);
        }
        if (packageMetadata.license) {
            lines.push(`- license: ${packageMetadata.license}`);
        }
        if (packageMetadata.packageManager) {
            lines.push(`- package manager: ${packageMetadata.packageManager}`);
        }

        if (packageMetadata.bin.length > 0) {
            lines.push("- bin:");
            for (const binEntry of packageMetadata.bin) {
                lines.push(`  - ${binEntry.name} -> ${binEntry.path}`);
            }
        }

        if (packageMetadata.scripts.length > 0) {
            lines.push("- scripts:");
            for (const script of packageMetadata.scripts) {
                lines.push(`  - ${script.name}: ${script.command}`);
            }
        }
    }

    lines.push(
        "",
        "## AI Development Notes",
        "- This is an npm CLI tool",
        "- Entry point: bin/cli.js",
        "- Template files are copied into user projects during init",
        "- template/ paths are runtime template sources; do not rewrite them as generated output paths",
        "- .claude/skills and ai/tests are generated in user projects when present in the template",
        "- Do not modify generated files unless explicitly required",
        "- Preserve package manager (npm/yarn/pnpm)",
        "- Follow existing file structure when adding new features",
    );

    lines.push("", "## Structure Overview");
    if (mergedStructure.length === 0) {
        lines.push("- No standard project structure detected");
    } else {
        lines.push(...formatDescriptiveList(mergedStructure));
    }

    lines.push("", "## Entry Points");
    if (entryPoints.length === 0) {
        lines.push("- No common entry files detected");
    } else {
        lines.push(...formatDescriptiveList(entryPoints));
    }

    lines.push("", "## Reusable System");
    for (const section of reusableSystem.sections) {
        lines.push(`### ${section.title}`);
        lines.push(...section.items.map((item) => `- ${item}`));
        lines.push("");
    }

    if (lines[lines.length - 1] === "") {
        lines.pop();
    }

    lines.push("", "## Risk Areas");
    if (risks.length === 0) {
        lines.push("- No obvious shared-risk areas detected");
    } else {
        lines.push(...risks.map((risk) => `- ${risk}`));
    }

    lines.push(
        "",
        "## Project Notes",
        "- Reuse existing structures before creating new ones",
        "- Treat shared modules cautiously and preserve backward compatibility",
        "- Keep changes minimal and localized unless the task explicitly requires broader refactoring",
    );

    return lines.join("\n");
}

export async function runScan(options = {}) {
    const mode = options.mode || "normal";
    const content = generateProjectMdContent();

    if (mode === "check") {
        const update = getProjectMdUpdate(content);

        if (!update.changed) {
            console.log("Project context is up to date.");
            return update;
        }

        console.log("Project context is outdated.");
        console.log("Run 'ai-dev-workflow scan' to update.");
        process.exitCode = 1;
        return update;
    }

    const update = updateProjectMd(content);

    if (!update.changed) {
        console.log(mode === "auto" ? "No changes." : "No changes.");
        return update;
    }

    if (update.skipped) {
        process.exitCode = 1;
        return update;
    }

    if (mode === "auto") {
        console.log("Project context updated.");
        return update;
    }

    console.log("Updated ai/project.md");
    console.log(
        "Review the AUTO-GENERATED section and add any project-specific notes under Manual Notes.",
    );

    return update;
}
